name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with "v", e.g. v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build & Publish Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release_install: false
          # Ensure it runs for the specific OS matrix
          mac: ${{ matrix.os == 'macos-latest' }}
          windows: ${{ matrix.os == 'windows-latest' }}
          linux: ${{ matrix.os == 'ubuntu-latest' }}
